"""
Alert endpoints for GOATGuard API.

GET   /alerts            — List all alerts (newest first)
PATCH /alerts/{id}/seen  — Mark an alert as seen

All endpoints require JWT authentication.
"""

import logging

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy.orm import Session
from typing import Optional, List

from src.api.dependencies import get_db, get_current_user_totp_verified
from src.database.models import User, Alert, Device

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/alerts", tags=["Alerts"])


class AlertResponse(BaseModel):
    """An alert generated by the analysis engine."""
    id: int
    device_id: int
    device_ip: Optional[str] = None
    device_hostname: Optional[str] = None
    anomaly_type: str
    description: str
    severity: str
    seen: bool
    timestamp: str


class AlertCountResponse(BaseModel):
    """Count of unseen alerts."""
    unseen_count: int
    total_count: int


@router.get("/", response_model=List[AlertResponse])
def list_alerts(
    seen: Optional[bool] = None,
    severity: Optional[str] = None,
    limit: int = 50,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user_totp_verified),
):
    """List alerts ordered by most recent first.

    Optional filters:
        seen: true/false to filter by read status
        severity: "low", "medium", "high", or "critical"
        limit: max number of alerts to return (default 50)
    """
    query = db.query(Alert).order_by(Alert.timestamp.desc())

    if seen is not None:
        query = query.filter(Alert.seen == seen)

    if severity is not None:
        query = query.filter(Alert.severity == severity)

    alerts = query.limit(limit).all()

    result = []
    for alert in alerts:
        device = db.query(Device).filter_by(id=alert.device_id).first()
        result.append({
            "id": alert.id,
            "device_id": alert.device_id,
            "device_ip": device.ip if device else None,
            "device_hostname": device.hostname if device else None,
            "anomaly_type": alert.anomaly_type,
            "description": alert.description,
            "severity": alert.severity,
            "seen": alert.seen,
            "timestamp": str(alert.timestamp),
        })

    return result


@router.get("/count", response_model=AlertCountResponse)
def get_alert_counts(
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user_totp_verified),
):
    """Get counts of unseen and total alerts.

    Useful for the notification badge in the mobile app.
    """
    total = db.query(Alert).count()
    unseen = db.query(Alert).filter_by(seen=False).count()

    return {
        "unseen_count": unseen,
        "total_count": total,
    }


@router.patch("/{alert_id}/seen")
def mark_alert_seen(
    alert_id: int,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user_totp_verified),
):
    """Mark an alert as seen by the administrator.

    Called when the admin opens/reads an alert in the mobile app.
    """
    alert = db.query(Alert).filter_by(id=alert_id).first()

    if not alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Alert not found",
        )

    alert.seen = True
    db.commit()

    return {"message": "Alert marked as seen", "alert_id": alert_id}